"""render_html plus its small helpers (strip_svg_wrapper, slides_to_json, lints)."""
import json
import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from slides import (  # noqa: E402
    Slide,
    render_html,
    slides_to_json,
    strip_svg_wrapper,
)


SAMPLE_SVG = (
    '<?xml version="1.0"?>\n'
    '<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "...">\n'
    '<!-- Generated by graphviz -->\n'
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10">'
    '<g class="node"><title>A</title></g>'
    '</svg>'
)


TEMPLATE = (
    '<!doctype html><html><head><title>{{TITLE_HTML}}</title></head>'
    '<body>{{SVG}}'
    '<script>window.__SLIDES__ = {{SLIDES_JSON}}; window.__TITLE__ = {{TITLE_JSON}};</script>'
    '</body></html>'
)


class TestStripSvgWrapper(unittest.TestCase):

    def test_drops_xml_doctype_and_comments(self):
        out = strip_svg_wrapper(SAMPLE_SVG)
        self.assertFalse(out.startswith("<?xml"))
        self.assertNotIn("<!DOCTYPE", out)
        self.assertNotIn("Generated by graphviz", out)
        self.assertTrue(out.startswith("<svg"))

    def test_idempotent(self):
        once = strip_svg_wrapper(SAMPLE_SVG)
        twice = strip_svg_wrapper(once)
        self.assertEqual(once, twice)


class TestSlidesToJson(unittest.TestCase):

    def test_bookends_with_overview(self):
        wrap = json.loads(slides_to_json([
            Slide(n=1, target="A", label="① A"),
            Slide(n=2, target="B", label="② B"),
        ]))
        self.assertEqual(wrap["mode"], "linear")
        slides = wrap["slides"]
        self.assertEqual(slides[0]["kind"], "overview")
        self.assertEqual(slides[-1]["kind"], "overview")
        self.assertEqual(
            [s.get("target") for s in slides],
            [None, "A", "B", None],
        )

    def test_empty_still_bookended(self):
        wrap = json.loads(slides_to_json([]))
        self.assertEqual(len(wrap["slides"]), 2)
        self.assertTrue(all(s["kind"] == "overview" for s in wrap["slides"]))

    def test_unicode_preserved(self):
        wrap = json.loads(slides_to_json([Slide(1, "A", "① Üñîçødé")]))
        self.assertEqual(wrap["slides"][1]["label"], "① Üñîçødé")


class TestRenderHtml(unittest.TestCase):

    def test_all_placeholders_replaced(self):
        out = render_html(TEMPLATE, SAMPLE_SVG, [Slide(1, "A", "① A")], "My Page")
        # No raw placeholder tokens should survive.
        for token in ("{{TITLE_HTML}}", "{{SVG}}", "{{SLIDES_JSON}}", "{{TITLE_JSON}}"):
            self.assertNotIn(token, out, f"placeholder {token} still present")

    def test_window_globals_preserved(self):
        # Regression: earlier placeholder convention __TITLE__ collided with the
        # runtime's window.__TITLE__ variable. {{…}} convention prevents that.
        out = render_html(TEMPLATE, SAMPLE_SVG, [], "Whatever")
        self.assertIn("window.__SLIDES__ =", out)
        self.assertIn("window.__TITLE__ =", out)

    def test_title_html_escaped(self):
        out = render_html(TEMPLATE, SAMPLE_SVG, [], "A & B")
        self.assertIn("A &amp; B", out)

    def test_title_json_escaped_for_script(self):
        out = render_html(TEMPLATE, SAMPLE_SVG, [], 'Hi "there"')
        # JSON-escaped form should appear inside the <script>.
        self.assertIn(r'window.__TITLE__ = "Hi \"there\""', out)

    def test_svg_inlined(self):
        out = render_html(TEMPLATE, SAMPLE_SVG, [], "X")
        self.assertIn('<svg xmlns="http://www.w3.org/2000/svg"', out)


if __name__ == "__main__":
    unittest.main()
